CREATE DEFINER=`root`@`%` PROCEDURE `Add_Course_ToCart`(IN p_user_id INT, IN p_course_id INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Block_User`(
CREATE DEFINER=`root`@`%` PROCEDURE `Buy_Course`(IN p_request_id VARCHAR(100))
CREATE DEFINER=`root`@`%` PROCEDURE `ChangeCategoryStatus`( In category_ID_ int, In status_ int  )
CREATE DEFINER=`root`@`%` PROCEDURE `ChangeStatus`( In category_ID_ int, In status_ int  )
CREATE DEFINER=`root`@`%` PROCEDURE `Change_Module_Order`(
CREATE DEFINER=`root`@`%` PROCEDURE `Change_Module_Status`(
CREATE DEFINER=`root`@`%` PROCEDURE `change_password`( IN p_password varchar(50),IN p_user_ID varchar(50),IN token_  varchar(50))
CREATE DEFINER=`root`@`%` PROCEDURE `Change_Student_Module_Lock_Status`(
CREATE DEFINER=`root`@`%` PROCEDURE `CheckStudentEnrollment`(
CREATE DEFINER=`root`@`%` PROCEDURE `Check_App_Version`(
CREATE DEFINER=`root`@`%` PROCEDURE `Check_Call_Availability`(
CREATE DEFINER=`root`@`%` PROCEDURE `Check_Options`(
CREATE DEFINER=`root`@`%` PROCEDURE `Check_OTP`(
CREATE DEFINER=`root`@`%` PROCEDURE `check_User`(
CREATE DEFINER=`root`@`%` PROCEDURE `Check_User_Blocked_Status`(
CREATE DEFINER=`root`@`%` PROCEDURE `Check_User_Exist`(
CREATE DEFINER=`root`@`%` PROCEDURE `deactivate_Account`(In mobile_Number INT )
CREATE DEFINER=`root`@`%` PROCEDURE `Delete_Batch`(
CREATE DEFINER=`root`@`%` PROCEDURE `Delete_course`( In course_id_ Int)
CREATE DEFINER=`root`@`%` PROCEDURE `Delete_course_category`( In course_category_Id_ Int)
CREATE DEFINER=`root`@`%` PROCEDURE `Delete_Course_Content`(IN Content_Id_ INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Delete_course_module`(
CREATE DEFINER=`root`@`%` PROCEDURE `Delete_Invoice`(in Invoice_Id_ Int)
CREATE DEFINER=`root`@`%` PROCEDURE `Delete_Student_Account`(
CREATE DEFINER=`root`@`%` PROCEDURE `delete_Student_Exam_result`(    IN p_StudentExam_ID INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Delete_User`(IN user_Id_ INT)
CREATE DEFINER=`root`@`%` PROCEDURE `enroleCourse`(
CREATE DEFINER=`root`@`%` PROCEDURE `enroleCourseFromAdmin`(
CREATE DEFINER=`root`@`%` PROCEDURE `Generate_certificate`(in StudentCourse_ID_ int,in value_ tinyint)
CREATE DEFINER=`root`@`%` PROCEDURE `GetAvailableUsers`(IN p_Student_ID INT)
CREATE DEFINER=`root`@`%` PROCEDURE `GetCallsAndChats`(
CREATE DEFINER=`root`@`%` PROCEDURE `GetStudentsByCourseId`( In course_Id_ Int)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_all_Batch`()
CREATE DEFINER=`root`@`%` PROCEDURE `Get_All_Course_Items`()
CREATE DEFINER=`root`@`%` PROCEDURE `Get_All_Live_Class`()
CREATE DEFINER=`root`@`%` PROCEDURE `Get_All_Menu`( )
CREATE DEFINER=`root`@`%` PROCEDURE `Get_All_Students`( In student_Name_ varchar(100))
CREATE DEFINER=`root`@`%` PROCEDURE `Get_All_Time_Slot`(IN CourseID INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_AppInfo`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_appinfo_List`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Available_Hod`(IN p_Student_ID INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Available_Mentors`(IN p_Student_ID INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Available_Time_Slot`(IN CourseID INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Batch`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Batch_Days`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Batch_Details`(IN batchID_ INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Batch_StudentList`(IN Batch_Id_ int )
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Blocked_User`(IN user_id INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Calls_And_Chats_List`(
CREATE DEFINER=`root`@`%` PROCEDURE `get_call_history`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_ChatList_Hod`(IN p_user_id INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Chats_Media`(
CREATE DEFINER=`root`@`%` PROCEDURE `get_chat_call_history`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Chat_With_Bot`( In student_ID_ Int)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Completed_Calls`(in p_teacher_id int)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Completed_liveClass`(IN p_teacher_id INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_course`(IN courseID INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_CourseContent_By_SectionAndStudent`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Courses_By_Category`( In category_ID_ varchar(100))
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Courses_By_StudentId`(
CREATE DEFINER=`root`@`%` PROCEDURE `get_course_Batches`(IN courseID INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Course_By_CourseId`(In Course_ID_ Int)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_course_category`( In course_category_Id_ Int)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_course_content`(IN courseID INT, IN Content_ID INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_course_content_By_Day`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_course_content_By_Module`(IN courseID INT, IN Module_ID_ INT )
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Course_Info`(In Course_ID_ Int)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Course_Module`()
CREATE DEFINER=`root`@`%` PROCEDURE `get_course_names`()
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Course_Reviews`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Course_Students`(IN course_Id_ INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Dashboard`()
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Dashboard_Data_By_StudentId`(IN studentID INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_DeviceId_By_UserId`(In senderId_ int,In isStudent_ Int)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_ExamDetails_By_StudentId`(
CREATE DEFINER=`root`@`%` PROCEDURE `get_Examof_Course`(IN p_course_id INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Exam_Days`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Exam_Days_By_Module`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Exam_Modules_By_CourseId`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Free_Time_Slot`(IN CourseID INT)
CREATE DEFINER=`root`@`%` PROCEDURE `get_hod_chat_history`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Hod_Course`(In p_user_Id INT )
CREATE DEFINER=`root`@`%` PROCEDURE `Get_InActive_Students`()
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Last_Day_Recordings`()
CREATE DEFINER=`root`@`%` PROCEDURE `Get_liveClass`(in p_teacher_id int )
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Live_Classes_By_CourseId`( In course_Id_ Int,IN UserId_ INT,IN Batch_Id_ INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Module_Of_Course`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_OneToOne_Recordings`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Ongoing_Calls`(in id_ int,in isStudent int)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_OnGoing_liveClass`(IN p_teacher_id INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Profile_Photo`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Recorded_LiveClasses`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Report_LiveClasses_By_BatchAndTeacher`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Report_StudentLiveClasses_By_BatchAndStudent`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Report_TeacherLiveClasses_By_BatchAndTeacher`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Sections_By_Course`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Specific_Exam_Details`(IN examID INT)
CREATE DEFINER=`root`@`localhost` PROCEDURE `Get_student`( In student_Id_ Int, in is_Student tinyInt)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Student_ClassRecords`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Student_ExamDetails`( IN p_Student_ID varchar(50),IN p_Exam_ID INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Student_Exam_Results`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Student_List_By_Batch`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Student_TimeSlots_By_TeacherID`(IN p_teacher_ID INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_teacherBatch_of_oneOnOne`(in id_ int)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_teachers`( In course_Id_ Int)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Teachers_By_Course`( In CourseId_ INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Teacher_courses`(IN user_Id_ Int)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Teacher_courses_With_Batch`(IN user_Id_ INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Teacher_Students`(
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Teacher_Timing`(IN teacherId_ INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_Upcomming_liveClass`(IN p_teacher_id INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_User`(IN user_Id_ INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_User_Cart`(IN user_id INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Get_User_Email_Number`( IN p_user_ID int)
CREATE DEFINER=`root`@`%` PROCEDURE `insert_chat_message`(
CREATE DEFINER=`root`@`%` PROCEDURE `insert_hod_chat_message`(
CREATE DEFINER=`root`@`localhost` PROCEDURE `Insert_Login_User`(
CREATE DEFINER=`root`@`%` PROCEDURE `Insert_Student_Exam_Result`(
CREATE DEFINER=`root`@`%` PROCEDURE `Login_Check`(
CREATE DEFINER=`root`@`%` PROCEDURE `mark_as_read`(
CREATE DEFINER=`root`@`%` PROCEDURE `Register_User_Request`(
CREATE DEFINER=`root`@`%` PROCEDURE `Remove_Course_FromCart`(IN user_id_ INT, IN course_id_ INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Report_User`(
CREATE DEFINER=`root`@`%` PROCEDURE `Review_Course`(
CREATE DEFINER=`root`@`%` PROCEDURE `Save_AppInfo`(
CREATE DEFINER=`root`@`%` PROCEDURE `Save_Batch`(IN Batch_Id_ INT, IN Course_ID_ INT, IN Batch_Name_ VARCHAR(100), IN scheduledTeachers JSON,
CREATE DEFINER=`root`@`%` PROCEDURE `Save_Call_History`(
CREATE DEFINER=`basil`@`%` PROCEDURE `Save_chatBot_message`( Student_ID_ int,Chat_Message_ text,IsReply_ tinyint, Chat_DateTime_ datetime, Delete_Status_ tinyint)
CREATE DEFINER=`root`@`%` PROCEDURE `save_course`(    IN CourseDetails JSON)
CREATE DEFINER=`root`@`%` PROCEDURE `Save_course_category`( In Category_ID_ int,
CREATE DEFINER=`root`@`%` PROCEDURE `save_course_content`(In ContentDetails JSON)
CREATE DEFINER=`root`@`%` PROCEDURE `Save_course_module`(
CREATE DEFINER=`root`@`%` PROCEDURE `Save_LiveClass`(
CREATE DEFINER=`root`@`%` PROCEDURE `Save_Occupation`(
CREATE DEFINER=`root`@`%` PROCEDURE `Save_OneToOne_Record_By_Link`(
CREATE DEFINER=`root`@`%` PROCEDURE `save_payment_request`(
CREATE DEFINER=`root`@`%` PROCEDURE `Save_student`( 
CREATE DEFINER=`root`@`%` PROCEDURE `Save_StudentLiveClass`(
CREATE DEFINER=`root`@`%` PROCEDURE `Save_Student_Exam`(
CREATE DEFINER=`root`@`%` PROCEDURE `Save_User`(
CREATE DEFINER=`root`@`%` PROCEDURE `Save_User_Invoice`(
CREATE DEFINER=`root`@`%` PROCEDURE `Search_Batch`(
CREATE DEFINER=`root`@`%` PROCEDURE `Search_course`(
CREATE DEFINER=`root`@`%` PROCEDURE `Search_course_category`(
CREATE DEFINER=`root`@`%` PROCEDURE `Search_course_module`(
CREATE DEFINER=`root`@`%` PROCEDURE `Search_menu`( In menu_Name_ varchar(100))
CREATE DEFINER=`root`@`%` PROCEDURE `Search_Occupations`()
CREATE DEFINER=`root`@`%` PROCEDURE `Search_Section`()
CREATE DEFINER=`root`@`%` PROCEDURE `Search_student`(
CREATE DEFINER=`root`@`%` PROCEDURE `Search_User`(
CREATE DEFINER=`root`@`%` PROCEDURE `Search_User_Invoice`(
CREATE DEFINER=`root`@`%` PROCEDURE `Student_Batch_Change`(
CREATE DEFINER=`root`@`%` PROCEDURE `Unblock_User`(
CREATE DEFINER=`root`@`%` PROCEDURE `Unlock_Exam`(
CREATE DEFINER=`root`@`%` PROCEDURE `UpdateThumbnailsRoundRobin`()
CREATE DEFINER=`root`@`%` PROCEDURE `Update_Call_Status`(
CREATE DEFINER=`root`@`%` PROCEDURE `Update_Cart_Course_Quantity`(IN user_id_ INT, IN course_id_ INT, IN new_quantity_ INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Update_LastAccessed_Content`(
CREATE DEFINER=`root`@`%` PROCEDURE `Update_LiveClass_RecordLink`(    IN p_LiveClass_ID INT)
CREATE DEFINER=`root`@`%` PROCEDURE `Update_Record_ClassLink`(
CREATE DEFINER=`root`@`%` PROCEDURE `Update_Record_Class_By_Link`(
CREATE DEFINER=`root`@`%` PROCEDURE `Update_Student_LastOnline`(
CREATE DEFINER=`root`@`%` PROCEDURE `Update_Time_Slot`(IN Student_ID_ INT, Course_ID_ INT,IN Slot_Id_ INT )
CREATE DEFINER=`root`@`%` PROCEDURE `Update_User_OTP`(
CREATE DEFINER=`root`@`%` PROCEDURE `update_user_status`(in User_ID_ int,IN status_ INT)
CREATE DEFINER=`root`@`%` PROCEDURE `ValidateTimeSlots`(
